#!/bin/bash
###########################
#清理归档和日志          ##
###########################

ARCHIVEDIR='/pgdata/archivedir'
LOG_PATH='/pgdata/log'
LOG='/home/postgres'

echo "清除前30天归档日志"
echo 'del starting'
find $ARCHIVEDIR -type f -mtime +30 - name '000*'|xargs -i rm -rf {} >> $LOG/dellog.log
echo 'del stoping' 

echo "清除前40天归档日志"
echo 'del starting'
find $LOG_PATH -type f -mtime +40 - name '000*'|xargs -i rm -rf {} >> $LOG/dellog.log
echo 'del stoping' 


from_collapse_limit=20;
join_collapse_limit=20;
geqo_threshold=20;
maintenance_io_concurrency = 300
track_activity_query_size = 4096


 echo "配置大页"
HP_SIZE=`grep Hugepagesize /proc/meminfo |awk '{print $2}'`
SHMEM_SIZE=`su - halo -c "psql -qxc \"select ceiling(sum(allocated_size)/1024) as SHMEM_SIZE from pg_shmem_allocations\" " |grep shmem_size|awk '{print $3}'`
NR_HP=`expr $(($SHMEM_SIZE / $HP_SIZE + 1))`

echo "修改服务器大页"
echo "vm.nr_hugepages=$NR_HP" >> /etc/sysctl.conf
sysctl -p
